apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "grafana-postgres.namespaceName" . }}
  labels:
    {{- include "grafana-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secretRef.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}