apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-postgres.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana-postgres.labels" . | nindent 6 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "grafana-postgres.selectorLabels" . | nindent 4 }}