# Default values for grafana-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

namespace: "" # Release Name 따라가지 않고, kube-prometheus-stack 앱이 설치된 namespace로 지정.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "grafana-postgres"

revisionHistoryLimit: 3

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  fsGroup: 999

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999

service:
  name: postgres-svc
  type: ClusterIP
  ports:
  - name: grafana-postgres
    port: 5432
    protocol: TCP
  # selector:
  #   app: postgres

probes:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


persistence:
  enabled: true
  name: data
  mountPath: /var/lib/postgresql/data
  accessModes:
  - ReadWriteOnce
  size: 20Gi
  storageClassName: gp3
pgdataSubdir: pgdata

nodeSelector: 
  role: ops

tolerations: 
  - effect: NoSchedule
    key: role
    operator: Equal
    value: ops

affinity: {}

initFiles:
  enabled: true
  name: init
  defaultMode: '0755'
  configMapName: postgres-init
  mountPath: /docker-entrypoint-initdb.d

# configMap 
configMap:
  name: postgres-init

# Secret 
secretRef:
  data:
    POSTGRES_DB: Z3JhZmFuYQ==
    POSTGRES_USER: YWRtaW4=
    POSTGRES_PASSWORD: "Zm1tc3lzb3BzMjAyNSEh"

httpRoute:
  enabled: false
ingress:
  enabled: false
